// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const chromeDriver = require("selenium-webdriver/chrome");
const assert = require('assert')
const { mkdtemp } = require('node:fs/promises');
const { join } = require('node:path');
const { tmpdir } = require('node:os');
const { rm } = require('node:fs/promises');

const browserList = ['chrome', 'firefox', 'safari'];


describe('standard flow', function () {
    this.timeout(30000);
    let driver;
    let vars;
    var options = new chromeDriver.Options();
    var tmp;

    beforeEach(async function () {
        tmp = await mkdtemp(join(tmpdir(), 'selenium-'));
        options.setUserPreferences({
            "download.default_directory": tmp,
        });
        options.addArguments("--accept-lang=de-DE");
        driver = await new Builder()
            .forBrowser('chrome')
            .setChromeOptions(options)
            .build();
        vars = {};
    })
    afterEach(async function () {
        await driver.quit();
        if (tmp && tmp.startsWith(join(tmpdir(), 'selenium-'))) {
            await rm(tmp, { recursive: true });
        }
    })

    it('standard flow', async function () {
        await driver.manage().setTimeouts({
            script: 20000,
            pageLoad: 20000,
            implicit: 20000,
        });
        await driver.get("https://www.dev-openpetition.de/opn-vote?demo=premiere&language=de_DE.utf8");
        await driver.manage().window().setRect({ width: 962, height: 1245 });
        await driver.findElement(By.xpath("//a[contains(text(),'Jetzt an Wahl teilnehmen')]")).click();
        await driver.findElement(By.id("Pfad_167")).click();
        await driver.findElement(By.xpath("//button[contains(.,\'Speichern\')]")).click();
        await driver.findElement(By.xpath("//button[contains(.,\'weiter zur Prüfung\')]")).click();
        await driver.findElement(By.xpath("//input[@type=\'file\']")).sendKeys(tmp + "/Wahlschlüssel.png");
        await driver.findElement(By.xpath("//button[contains(.,\'Wahlschein bestellen\')]")).click();
        await driver.executeScript("window.scrollTo(0,0)");
        await driver.findElement(By.xpath("//button[contains(.,\'Wahlschein bestellen\')]")).click();
        await driver.findElement(By.xpath("//input[@type=\'file\']")).sendKeys(tmp + "/Wahlschlüssel.png");
        await driver.findElement(By.css(".Button_secondary__egtBn")).click();
        await driver.findElement(By.id("voteselect_0_yes")).click();
        await driver.findElement(By.id("voteselect_1_no")).click();
        await driver.findElement(By.id("voteselect_2_no")).click();
        await driver.findElement(By.id("voteselect_3_no")).click();
        await driver.findElement(By.css(".Button_primary__JRIAm")).click();
    });
});
