import { Entity, Column, PrimaryGeneratedColumn, CreateDateColumn } from 'typeorm';

@Entity('blindedSignatures')
export class BlindedSignature {
  @PrimaryGeneratedColumn()
  id!: number; // Auto-generated

  @Column()
  userID!: number; // provided by AP

  @Column()
  electionID!: number; // provided by Smart Contract

  @Column({ type: 'varchar', length: 1026 })
  blindedToken!: string; // user generated

  @Column({ type: 'varchar', length: 1026 })
  blindedSignature!: string; // generated by Register

  @Column({ type: "varchar", nullable: true, default: null })
  txID?: string | null; // Gnosis TX ID publishing user registration

  @Column('text')
  jwt!: string; // todo: change to hashed jwt

  @CreateDateColumn()
  createdDate!: Date;
}