[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
[lint]
exclude_lints = ["asm-keccak256"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
